#!/bin/bash

#$ -S /bin/bash
#$ -M jontsai@uchicago.edu
#$ -N DSSMhinge1
#$ -m beasn
#$ -r n
#$ -o DSSMhinge1.out
#$ -e DSSMhinge1.err
#$ -cwd 

SETTING1="150x500" 
SETTING2="0.0"
SETTING3="100"
SETTING4="adam"
SETTING5="cos" 

export OMP_NUM_THREADS=2
export OPENBLAS_NUM_THREADS=2
echo "Start - `date`"
/home-nfs/jontsai/anaconda/bin/python DSSM_mlpave_train_hinge.py \
$SETTING1 $SETTING2 $SETTING3 $SETTING4 $SETTING5
echo "Finish - `date`"

