#!/bin/bash

#$ -S /bin/bash
#$ -M jontsai@uchicago.edu
#$ -N hier_GRU1_val
#$ -m beasn
#$ -r n
#$ -o hier_GRU1_val.out
#$ -e hier_GRU1_val.err
#$ -cwd 

SETTING1="300" 
SETTING2="0.0"
SETTING3="50" 
SETTING4="0.25"

export OMP_NUM_THREADS=2
export OPENBLAS_NUM_THREADS=2
echo "Start - `date`"
/home-nfs/jontsai/anaconda/bin/python BGRU2BGRU_val.py \
$SETTING1 $SETTING2 $SETTING3 $SETTING4
echo "Finish - `date`"

