#!/bin/bash

#$ -S /bin/bash
#$ -M jontsai@uchicago.edu
#$ -N hierBLSTM_val1-4
#$ -m beasn
#$ -r n
#$ -o hierBLSTM_val1-4.out
#$ -e hierBLSTM_val1-4.err
#$ -cwd 

SETTING1="300" 
SETTING2="0.0"
SETTING3="50" 
SETTING4="0.25"

export OMP_NUM_THREADS=2
export OPENBLAS_NUM_THREADS=2
echo "Start - `date`"
/home-nfs/jontsai/anaconda/bin/python BLSTM2BLSTM_val.py \
$SETTING1 $SETTING2 $SETTING3 $SETTING4
echo "Finish - `date`"

