#!/bin/bash

#$ -S /bin/bash
#$ -M jontsai@uchicago.edu
#$ -N HierRNN_pre3
#$ -m beasn
#$ -r n
#$ -o HierRNN_pre3.out
#$ -e HierRNN_pre3.err
#$ -cwd 

SETTING1="300" 
SETTING2="100"
SETTING5="most_simi_storyplot_pair" 

export OMP_NUM_THREADS=2
export OPENBLAS_NUM_THREADS=2
echo "Start - `date`"
/home-nfs/jontsai/anaconda/bin/python BLSTM_attention_precal_train.py \
$SETTING1 $SETTING2 $SETTING3
echo "Finish - `date`"

